on:
  push:
    branches:
      - testfads
jobs:
  build_and_preview:
    name: Build & Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Deploy Preview
        uses: w9jds/firebase-action@master
        env:
         firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NEW23_768DF }}'
        with:
          args: hosting:channel:deploy --project demodfsaf